const collection = [
    {
        name: "AT-AT Driver",
        number: 75429,
        releaseYear: 2025,
        pieces: 730,
        retired: "No",
        retail: 69.99,
        value: 75.31,
        theme: "Star Wars",
        subtheme: "Helmet Collection",
        img: "75429.png",
    },
    {
        name: "Jango Fett",
        number: 75408,
        releaseYear: 2025,
        pieces: 616,
        retired: "No",
        retail: 69.99,
        value: 61.21,
        theme: "Star Wars",
        subtheme: "Helmet Collection",
        img: "75408.png",
    },
    {
        name: "Kylo Ren",
        number: 75415,
        releaseYear: 2025,
        pieces: 529,
        retired: "No",
        retail: 69.99,
        value: 67.15,
        theme: "Star Wars",
        subtheme: "Helmet Collection",
        img: "75415.png",
    },
    {
        name: "Captain Rex",
        number: 75349,
        releaseYear: 2023,
        pieces: 854,
        retired: "No",
        retail: 69.99,
        value: 62.95,
        theme: "Star Wars",
        subtheme: "Helmet Collection",
        img: "75349.png",
    },
    {
        name: "Clone Commander Cody",
        number: 75350,
        releaseYear: 2023,
        pieces: 766,
        retired: "Yes",
        retail: 69.99,
        value: 66.70,
        theme: "Star Wars",
        subtheme: "Helmet Collection",
        img: "75350.png",
    },
    {
        name: "Princess Leia (Boushh)",
        number: 75351,
        releaseYear: 2023,
        pieces: 670,
        retired: "Yes",
        retail: 69.99,
        value: 83.58,
        theme: "Star Wars",
        subtheme: "Helmet Collection",
        img: "75351.png",
    },
    {
        name: "Dark Trooper",
        number: 75343,
        releaseYear: 2022,
        pieces: 693,
        retired: "Yes",
        retail: 69.99,
        value: 89.99,
        theme: "Star Wars",
        subtheme: "Helmet Collection",
        img: "75343.png",
    },
    {
        name: "Luke Skywalker Red Five",
        number: 75327,
        releaseYear: 2022,
        pieces: 675,
        retired: "Yes",
        retail: 69.99,
        value: 79.98,
        theme: "Star Wars",
        subtheme: "Helmet Collection",
        img: "75327.png",
    },
    {
        name: "The Mandalorian",
        number: 75328,
        releaseYear: 2022,
        pieces: 584,
        retired: "No",
        retail: 69.99,
        value: 56.49,
        theme: "Star Wars",
        subtheme: "Helmet Collection",
        img: "75328.png",
    },
    {
        name: "Darth Vader",
        number: 75304,
        releaseYear: 2021,
        pieces: 834,
        retired: "No",
        retail: 79.99,
        value: 66.95,
        theme: "Star Wars",
        subtheme: "Helmet Collection",
        img: "75304.png",
    },
    {
        name: "Scout Trooper",
        number: 75305,
        releaseYear: 2021,
        pieces: 471,
        retired: "Yes",
        retail: 49.99,
        value: 102.92,
        theme: "Star Wars",
        subtheme: "Helmet Collection",
        img: "75305.png",
    },
    {
        name: "TIE Fighter Pilot",
        number: 75274,
        releaseYear: 2020,
        pieces: 724,
        retired: "Yes",
        retail: 59.99,
        value: 347.11,
        theme: "Star Wars",
        subtheme: "Helmet Collection",
        img: "75274.png",
    },
    {
        name: "Stormtrooper",
        number: 75276,
        releaseYear: 2020,
        pieces: 647,
        retired: "Yes",
        retail: 59.99,
        value: 195.29,
        theme: "Star Wars",
        subtheme: "Helmet Collection",
        img: "75276.png",
    },
    {
        name: "Boba Fett",
        number: 75277,
        releaseYear: 2020,
        pieces: 625,
        retired: "Yes",
        retail: 59.99,
        value: 93.57,
        theme: "Star Wars",
        subtheme: "Helmet Collection",
        img: "75277.png",
    },
    {
        name: "Sith Infiltrator",
        number: 75383,
        releaseYear: 2024,
        pieces: 640,
        retired: "No",
        retail: 69.99,
        value: 69.23,
        theme: "Star Wars",
        subtheme: "Episode I",
        img: "75383.png",
    },
    {
        name: "Builable Droideka",
        number: 75381,
        releaseYear: 2024,
        pieces: 583,
        retired: "No",
        retail: 64.99,
        value: 53.59,
        theme: "Star Wars",
        subtheme: "Episode I",
        img: "75381.png",
    },
    {
        name: "Naboo Starfighter",
        number: 75092,
        releaseYear: 2015,
        pieces: 442,
        retired: "Yes",
        retail: 49.99,
        value: 188.65,
        theme: "Star Wars",
        subtheme: "Episode I",
        img: "75092.png",
    },
    {
        name: "AAT",
        number: 30680,
        releaseYear: 2024,
        pieces: 75,
        retired: "Yes",
        retail: 4.99,
        value: 7.62,
        theme: "Star Wars",
        subtheme: "Episode I",
        img: "30680.png",
    },
    {
        name: "Obi-Wan Kenobi's Jedi Starfighter",
        number: 75333,
        releaseYear: 2022,
        pieces: 282,
        retired: "No",
        retail: 29.99,
        value: 24.83,
        theme: "Star Wars",
        subtheme: "Episode II",
        img: "75333.png",
    },
    {
        name: "ARC-170 Starfighter",
        number: 75402,
        releaseYear: 2025,
        pieces: 497,
        retired: "No",
        retail: 69.99,
        value: 56.34,
        theme: "Star Wars",
        subtheme: "Episode III",
        img: "75402.png",
    },
    {
        name: "Anakin's Jedi Interceptor",
        number: 75281,
        releaseYear: 2020,
        pieces: 248,
        retired: "Yes",
        retail: 29.99,
        value: 126.11,
        theme: "Star Wars",
        subtheme: "Episode III",
        img: "75281.png",
    },
    {
        name: "Clone Scout Walker - 20th Anniversary Edition",
        number: 75261,
        releaseYear: 2019,
        pieces: 250,
        retired: "Yes",
        retail: 29.99,
        value: 98.41,
        theme: "Star Wars",
        subtheme: "Episode III",
        img: "75261.png",
    },
    {
        name: "Imperial Star Destroyer",
        number: 75394,
        releaseYear: 2024,
        pieces: 1555,
        retired: "No",
        retail: 159.99,
        value: 157.60,
        theme: "Star Wars",
        subtheme: "Episode IV",
        img: "75394.png",
    },
    {
        name: "Luke Skywalker's X-Wing Fighter",
        number: 75301,
        releaseYear: 2021,
        pieces: 474,
        retired: "Yes",
        retail: 49.99,
        value: 60.00,
        theme: "Star Wars",
        subtheme: "Episode IV",
        img: "75301.png",
    },
    {
        name: "Imperial TIE Fighter",
        number: 75300,
        releaseYear: 2021,
        pieces: 432,
        retired: "Yes",
        retail: 44.99,
        value: 51.95,
        theme: "Star Wars",
        subtheme: "Episode IV",
        img: "75300.png",
    },
    {
        name: "Luke Skywalker's Landspeeder",
        number: 75271,
        releaseYear: 2020,
        pieces: 236,
        retired: "Yes",
        retail: 29.99,
        value: 43.82,
        theme: "Star Wars",
        subtheme: "Episode IV",
        img: "75271.png",
    },
    {
        name: "Millennium Falcon",
        number: 30708,
        releaseYear: 2025,
        pieces: 74,
        retired: "No",
        retail: 4.99,
        value: 5.34,
        theme: "Star Wars",
        subtheme: "Episode IV",
        img: "30708.png",
    },
    {
        name: "Hoth Attack",
        number: 75138,
        releaseYear: 2016,
        pieces: 233,
        retired: "Yes",
        retail: 24.99,
        value: 76.23,
        theme: "Star Wars",
        subtheme: "Episode V",
        img: "75138.png",
    },
    {
        name: "Yoda's Hut",
        number: 75208,
        releaseYear: 2018,
        pieces: 229,
        retired: "Yes",
        retail: 29.99,
        value: 44.45,
        theme: "Star Wars",
        subtheme: "Episode V",
        img: "75208.png",
    },
    {
        name: "AT-ST",
        number: 30495,
        releaseYear: 2022,
        pieces: 79,
        retired: "Yes",
        retail: 4.99,
        value: 9.99,
        theme: "Star Wars",
        subtheme: "Episode V",
        img: "30495.png",
    }, 
    {
        name: "TIE Interceptor",
        number: 30685,
        releaseYear: 2024,
        pieces: 48,
        retired: "Yes",
        retail: 4.99,
        value: 9.40,
        theme: "Star Wars",
        subtheme: "Episode VI",
        img: "30685.png",
    },
    {
        name: "TIE Bomber",
        number: 75347,
        releaseYear: 2023,
        pieces: 625,
        retired: "No",
        retail: 64.99,
        value: 52.26,
        theme: "Star Wars",
        subtheme: "Episode VI",
        img: "75347.png",
    },
    {
        name: "Imperial Shuttle",
        number: 75302,
        releaseYear: 2021,
        pieces: 660,
        retired: "Yes",
        retail: 69.99,
        value: 79.69,
        theme: "Star Wars",
        subtheme: "Episode VI",
        img: "75302.png",
    },
    {
        name: "TIE Fighter",
        number: 8028,
        releaseYear: 2008,
        pieces: 44,
        retired: "Yes",
        retail: 4.99,
        value: 9.28,
        theme: "Star Wars",
        subtheme: "Mini Building Set",
        img: "8028.png",
    },     
    {
        name: "Battle of Hoth - 20th Anniversary Edition",
        number: 40333,
        releaseYear: 2019,
        pieces: 195,
        retired: "Yes",
        retail: 0.00,
        value: 48.29,
        theme: "Star Wars",
        subtheme: "Promotional",
        img: "40333.png",
    }, 
    {
        name: "Rebuild The Galaxy The Dark Falcon",
        number: 75389,
        releaseYear: 2024,
        pieces: 1579,
        retired: "No",
        retail: 179.99,
        value: 145.86,
        theme: "Star Wars",
        subtheme: "Rebuild the Galaxy",
        img: "75389.png",
    },
    {
        name: "Y-wing Starfighter",
        number: 75172,
        releaseYear: 2017,
        pieces: 691,
        retired: "Yes",
        retail: 59.99,
        value: 176.31,
        theme: "Star Wars",
        subtheme: "Rogue One",
        img: "75172.png",
    },
    {
        name: "Han Solo's Landspeeder",
        number: 75209,
        releaseYear: 2018,
        pieces: 345,
        retired: "Yes",
        retail: 29.99,
        value: 44.99,
        theme: "Star Wars",
        subtheme: "Solo",
        img: "75209.png",
    },
    {
        name: "Imperial TIE Fighter",
        number: 75211,
        releaseYear: 2018,
        pieces: 519,
        retired: "Yes",
        retail: 69.99,
        value: 249.29,
        theme: "Star Wars",
        subtheme: "Solo",
        img: "75211.png",
    }, 
    {
        name: "Acclamator-Class Assault Ship",
        number: 75404,
        releaseYear: 2025,
        pieces: 450,
        retired: "No",
        retail: 49.99,
        value: 42.74,
        theme: "Star Wars",
        subtheme: "Starship Collection",
        img: "75404.png",
    },
    {
        name: "Millennium Falcon",
        number: 75375,
        releaseYear: 2024,
        pieces: 921,
        retired: "No",
        retail: 84.99,
        value: 69.53,
        theme: "Star Wars",
        subtheme: "Starship Collection",
        img: "75375.png",
    },
    {
        name: "The Mandalorian's N-1 Starfighter",
        number: 75325,
        releaseYear: 2022,
        pieces: 412,
        retired: "No",
        retail: 59.99,
        value: 47.74,
        theme: "Star Wars",
        subtheme: "The Book of Boba Fett",
        img: "75325.png",
    },
    {
        name: "Ahsoka's Jedi Interceptor",
        number: 75401,
        releaseYear: 2025,
        pieces: 290,
        retired: "No",
        retail: 44.99,
        value: 39.18,
        theme: "Star Wars",
        subtheme: "The Clone Wars",
        img: "75401.png",
    },
    {
        name: "Clone Trooper & Battle Droid Battle Pack",
        number: 75372,
        releaseYear: 2024,
        pieces: 215,
        retired: "No",
        retail: 29.99,
        value: 26.11,
        theme: "Star Wars",
        subtheme: "The Clone Wars",
        img: "75372.png",
    },
    {
        name: "Coruscant Guard Gunship",
        number: 75354,
        releaseYear: 2023,
        pieces: 1083,
        retired: "No",
        retail: 139.99,
        value: 126.36,
        theme: "Star Wars",
        subtheme: "The Clone Wars",
        img: "75354.png",
    },
    {
        name: "501st Clone Troopers Battle Pack",
        number: 75345,
        releaseYear: 2023,
        pieces: 119,
        retired: "No",
        retail: 19.99,
        value: 17.38,
        theme: "Star Wars",
        subtheme: "The Clone Wars",
        img: "75345.png",
    },
    {
        name: "332nd Ahsoka's Clone Trooper Battle Pack",
        number: 75359,
        releaseYear: 2023,
        pieces: 108,
        retired: "Retired",
        retail: 19.99,
        value: 24.99,
        theme: "Star Wars",
        subtheme: "The Clone Wars",
        img: "75359.png",
    },
    {
        name: "Republic Fighter Tank",
        number: 75342,
        releaseYear: 2022,
        pieces: 262,
        retired: "Yes",
        retail: 39.99,
        value: 44.99,
        theme: "Star Wars",
        subtheme: "The Clone Wars",
        img: "75342.png",
    },
    {
        name: "Mandalorian Starfighter",
        number: 75316,
        releaseYear: 2021,
        pieces: 544,
        retired: "Yes",
        retail: 59.99,
        value: 64.99,
        theme: "Star Wars",
        subtheme: "The Clone Wars", 
        img: "75316.png",
    },
    {
        name: "Anakin's Jedi Starfighter",
        number: 75214,
        releaseYear: 2018,
        pieces: 247,
        retired: "Yes",
        retail: 19.99,
        value: 80.00,
        theme: "Star Wars",
        subtheme: "The Clone Wars",
        img: "75214.png",
    },
    {
        name: "Droid Tri-Fighter",
        number: 8086,
        releaseYear: 2010,
        pieces: 268,
        retired: "Yes",
        retail: 24.99,
        value: 101.15,
        theme: "Star Wars",
        subtheme: "The Clone Wars",
        img: "8086.png",
    },
    {
        name: "First Order Snowspeeder",
        number: 75100,
        releaseYear: 2015,
        pieces: 444,
        retired: "Yes",
        retail: 39.99,
        value: 61.69,
        theme: "Star Wars",
        subtheme: "The Force Awakens",
        img: "75100.png",
    },
    {
        name: "AT-ST Raider",
        number: 75254,
        releaseYear: 2019,
        pieces: 540,
        retired: "Yes",
        retail: 49.99,
        value: 40.69,
        theme: "Star Wars",
        subtheme: "The Mandalorian",
        img: "75254.png",
    },
    {
        name: "Ambush on Mandalore Battle Pack",
        number: 75373,
        releaseYear: 2024,
        pieces: 109,
        retired: "No",
        retail: 19.99,
        value: 18.04,
        theme: "Star Wars",
        subtheme: "The Mandalorian",
        img: "75373.png",
    },
    {
        name: "Trouble on Tatooine",
        number: 75299,
        releaseYear: 2021,
        pieces: 276,
        retired: "Yes",
        retail: 29.99,
        value: 24.99,
        theme: "Star Wars",
        subtheme: "The Mandalorian",
        img: "75299.png",
    },
    {
        name: "The Armorer's Manadalorian Forge",
        number: 75319,
        releaseYear: 2021,
        pieces: 258,
        retired: "Yes",
        retail: 29.99,
        value: 44.99,
        theme: "Star Wars",
        subtheme: "The Mandalorian",
        img: "75319.png",
    },
    {
        name: "The Child",
        number: 75318,
        releaseYear: 2020,
        pieces: 1073,
        retired: "Yes",
        retail: 89.99,
        value: 74.00,
        theme: "Star Wars",
        subtheme: "The Mandalorian",    
        img: "75318.png",
    },
    {
        name: "The Razor Crest",
        number: 75292,
        releaseYear: 2020,
        pieces: 1023,
        retired: "Yes",
        retail: 139.99,
        value: 125.29,
        theme: "Star Wars",
        subtheme: "The Mandalorian",
        img: "75292.png",
    },
    {
        name: "Poe Dameron's X-Wing Fighter",
        number: 75273,
        releaseYear: 2020,
        pieces: 761,
        retired: "Yes",
        retail: 89.99,
        value: 100.00,
        theme: "Star Wars",
        subtheme: "The Rise of Skywalker",
        img: "75273.png",
    },
    {
        name: "Poe Dameron's X-Wing Fighter",
        number: 30386,
        releaseYear: 2020,
        pieces: 72,
        retired: "Yes",
        retail: 4.97,
        value: 10.18,
        theme: "Star Wars",
        subtheme: "The Rise of Skywalker",
        img: "30386.png",
    },
    {
        name: "Millennium Falcon",
        number: 75257,
        releaseYear: 2019,
        pieces: 1351,
        retired: "Yes",
        retail: 169.99,
        value: 177.87,
        theme: "Star Wars",
        subtheme: "The Rise of Skywalker",
        img: "75257.png",
    },
    {
        name: "Resistance Y-Wing Starfighter",
        number: 75249,
        releaseYear: 2019,
        pieces: 578,
        retired: "Yes",
        retail: 69.99,
        value: 69.96,
        theme: "Star Wars",
        subtheme: "The Rise of Skywalker",
        img: "75249.png",
    },
    {
        name: "Resistance A-Wing Starfighter",
        number: 75248,
        releaseYear: 2019,
        pieces: 269,
        retired: "Yes",
        retail: 29.99,
        value: 40.44,
        theme: "Star Wars",
        subtheme: "The Rise of Skywalker",
        img: "75248.png",
    },
    {
        name: "Buildable C-3PO",
        number: 75398,
        releaseYear: 2024,
        pieces: 1132,
        retired: "No",
        retail: 149.99,
        value: 119.89,
        theme: "Star Wars",
        subtheme: "Miscellaneous",
        img: "75398.png",
    },
    {
        name: "Buildable R2-D2",
        number: 75379,
        releaseYear: 2024,
        pieces: 1050,
        retired: "No",
        retail: 99.99,
        value: 87.36,
        theme: "Star Wars",
        subtheme: "Miscellaneous",
        img: "75379.png",
    },
    {
        name: "Brick-Built Star Wars Logo",
        number: 75407,
        releaseYear: 2025,
        pieces: 700,
        retired: "No",
        retail: 59.99,
        value: 53.21,
        theme: "Star Wars",
        subtheme: "Miscellaneous",
        img: "75407.png",
    },
    {
        name: "General Grevious",
        number: 75112,
        releaseYear: 2015,
        pieces: 186,
        retired: "Yes",
        retail: 34.99,
        value: 178.75,
        theme: "Star Wars",
        subtheme: "Buildable Figures",
        img: "75112.png",
    },
    {
        name: "Patrol Vehicle",
        number: 30585,
        releaseYear: 2022,
        pieces: 45,
        retired: "Yes",
        retail: 4.99,
        value: 9.99,
        theme: "City",
        subtheme: "Fire",
        img: "30585.png",
    },
    {
        name: "Retro Camera",
        number: 31147,
        releaseYear: 2024,
        pieces: 261,
        retired: "No",
        retail: 19.99,
        value: 18.27,
        theme: "Creator",
        subtheme: "Three-in-One",
        img: "31147.png",
    },
    {
        name: "Space Shuttle Adventure",
        number: 31117,
        releaseYear: 2021,
        pieces: 486,
        retired: "Yes",
        retail: 39.99,
        value: 54.99,
        theme: "Creator",
        subtheme: "Three-in-One",
        img: "31117.png",
    },
    {
        name: "Shuttle Transporter",
        number: 31091,
        releaseYear: 2019,
        pieces: 341,
        retired: "Yes",
        retail: 24.99,
        value: 40.14,
        theme: "Creator",
        subtheme: "Three-in-One",
        img: "31091.png",
    },
    {
        name: "Sunset Track Racer",
        number: 31089,
        releaseYear: 2019,
        pieces: 221,
        retired: "Yes",
        retail: 19.99,
        value: 23.95,
        theme: "Creator",
        subtheme: "Three-in-One",
        img: "31089.png",
    },
    {
        name: "Futuristic Flyer",
        number: 31086,
        releaseYear: 2019,
        pieces: 157,
        retired: "Yes",
        retail: 14.99,
        value: 25.47,
        theme: "Creator",
        subtheme: "Three-in-One",
        img: "31086.png",
    },
    {
        name: "Bonsai Tree",
        number: 10281,
        releaseYear: 2021,
        pieces: 878,
        retired: "No",
        retail: 49.99,
        value: 40.92,
        theme: "Icons",
        subtheme: "Botanical Collection",
        img: "10281.png",
    },
    {
        name: "TRON Legacy",
        number: 21314,
        releaseYear: 2018,
        pieces: 230,
        retired: "Yes",
        retail: 34.99,
        value: 191.46,
        theme: "Ideas",
        subtheme: "Licensed",
        img: "21314.png",
    },
    {
        name: "Space Planet Earth and Moon in Orbit",
        number: 42179,
        releaseYear: 2024,
        pieces: 526,
        retired: "No",
        retail: 79.99,
        value: 69.18,
        theme: "Technic",
        subtheme: "Space",
        img: "42179.png",
    },
    {
        name: "NASCAR Next Gen Chevrolet Camaro ZL1",
        number: 42153,
        releaseYear: 2023,
        pieces: 672,
        retired: "Yes",
        retail: 49.99,
        value: 52.93,
        theme: "Technic",
        subtheme: "Licensed",
        img: "42153.png",
    },
    {
        name: "Dragster",
        number: 42103,
        releaseYear: 2020,
        pieces: 225,
        retired: "Yes",
        retail: 19.99,
        value: 26.58,
        theme: "Technic",
        subtheme: "Miscellaneous",
        img: "42103.png",
    },
    {
        name: "Chevrolet Corvette ZR1",
        number: 42093,
        releaseYear: 2019,
        pieces: 579,
        retired: "Yes",
        retail: 49.99,
        value: 54.99,
        theme: "Technic",
        subtheme: "Miscellaneous",
        img: "42093.png",
    },
    {
        name: "First Responder",
        number: 42075,
        releaseYear: 2018,
        pieces: 513,
        retired: "Yes",
        retail: 49.99,
        value: 75.91,
        theme: "Technic",
        subtheme: "Miscellaneous",
        img: "42075.png",
    },
    {
        name: "Ultralight Helicopter",
        number: 42057,
        releaseYear: 2017,
        pieces: 199,
        retired: "Yes",
        retail: 19.99,
        value: 40.13,
        theme: "Technic",
        subtheme: "Miscellaneous",
        img: "42057.png",
    },
    {
        name: "Mustang Dark Horse",
        number: 76920,
        releaseYear: 2024,
        pieces: 344,
        retired: "No",
        retail: 26.99,
        value: 24.02,
        theme: "Speed Champions",
        subtheme: "Ford",
        img: "76920.png",
    },
    {
        name: "GT Heritage Edition and Bronco R",
        number: 76905,
        releaseYear: 2021,
        pieces: 660,
        retired: "Yes",
        retail: 49.99,
        value: 89.96,
        theme: "Speed Champions",
        subtheme: "Ford",
        img: "76905.png",
    },
    {
        name: "Countach",
        number: 76908,
        releaseYear: 2022,
        pieces: 262,
        retired: "Yes",
        retail: 19.99,
        value: 23.96,
        theme: "Speed Champions",
        subtheme: "Lamborghini",
        img: "76908.png",
    },
    {
        name: "Urus ST-X & Huracan Super Trofeo EVO",
        number: 76899,
        releaseYear: 2020,
        pieces: 663,
        retired: "Yes",
        retail: 49.99,
        value: 90.31,
        theme: "Speed Champions",
        subtheme: "Lamborghini",
        img: "76899.png",
    },
    {
        name: "Hurcan Super Trofeo EVO",
        number: 30342,
        releaseYear: 2020,
        pieces: 69,
        retired: "Yes",
        retail: 0.00,
        value: 5.02,
        theme: "Speed Champions",
        subtheme: "Lamborghini",
        img: "30342.png",
    },
    {
        name: "Valkyrie AMR Pro",
        number: 30434,
        releaseYear: 2022,
        pieces: 97,
        retired: "Yes",
        retail: 4.99,
        value: 9.70,
        theme: "Speed Champions",
        subtheme: "Aston Martin",
        img: "30434.png",
    },
    {
        name: "Corvette C8.R Race Care and 1968 Chevrolet Corvette",
        number: 76903,
        releaseYear: 2021,
        pieces: 512,
        retired: "Yes",
        retail: 29.99,
        value: 45.33,
        theme: "Speed Champions",
        subtheme: "Chevrolet",
        img: "76903.png",
    },
    {
        name: "GR Supra",
        number: 76901,
        releaseYear: 2021,
        pieces: 299,
        retired: "Yes",
        retail: 19.99,
        value: 27.96,
        theme: "Speed Champions",
        subtheme: "Toyota",
        img: "76901.png",
    },
    {
        name: "Jesko",
        number: 76900,
        releaseYear: 2021,
        pieces: 280,
        retired: "Yes",
        retail: 19.99,
        value: 24.99,
        theme: "Speed Champions",
        subtheme: "Koenigsegg",
        img: "76900.png",
    },
    {
        name: "Elva",
        number: 76902,
        releaseYear: 2021,
        pieces: 263,
        retired: "Yes",
        retail: 19.99,
        value: 26.84,
        theme: "Speed Champions",
        subtheme: "Mclaren",
        img: "76902.png",
    },
    {
        name: "Elva",
        number: 30343,
        releaseYear: 2021,
        pieces: 85,
        retired: "Yes",
        retail: 3.99,
        value: 9.99,
        theme: "Speed Champions",
        subtheme: "Mclaren",
        img: "30343.png",
    },
    {
        name: "Senna",
        number: 75892,
        releaseYear: 2019,
        pieces: 219,
        retired: "Yes",
        retail: 14.99,
        value: 24.28,
        theme: "Speed Champions",
        subtheme: "Mclaren",
        img: "75892.png",
    },
    {
        name: "Formula E Panasonic Jaguar Racing GEN2 Car & Jaguar I-PACE eTROPHY",
        number: 76898,
        releaseYear: 2020,
        pieces: 565,
        retired: "Yes",
        retail: 29.99,
        value: 61.61,
        theme: "Speed Champions",
        subtheme: "Jaguar",
        img: "76898.png",
    },
    {
        name: "GT-R NISMO",
        number: 76896,
        releaseYear: 2020,
        pieces: 298,
        retired: "Yes",
        retail: 19.99,
        value: 46.42,
        theme: "Speed Champions",
        subtheme: "Nissan",
        img: "76896.png",
    },
    {
        name: "F8 Tributo",
        number: 76895,
        releaseYear: 2020,
        pieces: 275,
        retired: "Yes",
        retail: 19.99,
        value: 34.96,
        theme: "Speed Champions",
        subtheme: "Ferrari",    
        img: "76895.png",
    },
    {
        name: "Sport Quattro S1",
        number: 76897,
        releaseYear: 2020,
        pieces: 250,
        retired: "Yes",
        retail: 19.99,
        value: 58.15,
        theme: "Speed Champions",
        subtheme: "Audi",
        img: "76897.png",
    },
    {
        name: "911 Turbo 3.0",
        number: 75895,
        releaseYear: 2019,
        pieces: 180,
        retired: "Yes",
        retail: 14.99,
        value: 49.00,
        theme: "Speed Champions",
        subtheme: "Porsche",
        img: "75895.png",
    },
];